project:
  type: website

website:
  title: "Shaon Lahiri, PhD, MPH"
  favicon: favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: CV.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: Teaching.qmd
        text: Teaching
      - href: https://web.sas.upenn.edu/cringescale/
        text: Cringe
      

format:
  html:
    theme: 
      light: yeti
      dark: vapor
    css: styles.css
    toc: false
    page-layout: full

editor: visual

