---
title: "Teaching"
title-block-banner: "#4100AB"
---

I have been teaching undergraduate and Master's students since 2018, and greatly enjoy the process of developing course content and teaching. I have experience teaching courses in-person, online, and in a hybrid model. The following are a list of courses for which I have either been a teaching assistant or a sole instructor.

## University of Pennsylvania 

I create and teach courses for advanced undergraduates in the Philosophy, Politics & Economics program at the University of Pennsylvania.

***PPE 4850. Advanced Seminar in Research Methods** (Spring 2024).

**PPE 4800. Social Norms, Networks, and Influence** (Fall 2023).

**PPE 4800.** **Theories of Behavior Change** (Spring 2023).

**PPE 4800. Unpacking the Black Box: Tackling Big Issues in Social & Behavioral Science Interventions** (Fall 2022).

**PPE 4000. Research Transparency, Reproducibility, and Basic Data Analysis in R** (Spring & Fall 2023).

## The George Washington University

I was a teaching assistant for undergraduate and Master's students in public health for four years. I was also an adjunct lecturer (sole instructor) for an online course (PUBH 6052) for one year.

**PUBH 6052. Practical Data Management and Analysis for Public Health** (Fall 2021 & Spring 2022).

**PUBH 6007. Social & Behavioral Approaches to Health** (Spring 2019, Spring 2020, Spring 2021, Fall 2021 & Spring 2022).

**PUBH 6504. Social & Behavioral Research Methods** (Fall 2018, Fall 2019 & Fall 2020).

**PUBH 6009**. **Fundamentals of Public Health Program Evaluation** (Spring 2020).

**PUBH 6503. Public Health Marketing** (Fall 2019).

**PUBH 4140. Writing in the Discipline of Public Health** (Spring 2019).
