---
title: "Multidisciplinary team processes parallel natural disaster preparedness and response: A qualitative case study"
type: "article"
author: "<strong>Shaon Lahiri</strong>, Bobbi Snowden, Jiayan Gu, Nandita Krishnan, Hannah Yellin, Khadidiatou Ndiaye"
year: "2021"
publication: "International Journal of Disaster Risk Reduction"
doi: "https://doi.org/10.1016/j.ijdrr.2021.102369"
toc: false
categories:
  - cross-disciplinary teams 
  - team science
  - natural disaster preparedness
  - qualitative research
  - sustainability
---

## Citation (APA 7)

> Lahiri, S., Snowden, B., Gu, J., Krishnan, N., Yellin, H., & Ndiaye, K. (2021). Multidisciplinary team processes parallel natural disaster preparedness and response: A qualitative case study. *International Journal of Disaster Risk Reduction*, *61*, 102369.

## Abstract

Cross-disciplinary (multidisciplinary, interdisciplinary, or transdisciplinary) teams are increasingly recognized as crucial alliances required for solving complex problems, particularly those attributable to natural disasters. Despite this recognition, there has been limited research examining the factors necessary for successful cross-disciplinary collaboration at the outset of a research initiative to address natural [disaster preparedness](https://www-sciencedirect-com.proxy.library.upenn.edu/topics/earth-and-planetary-sciences/disaster-preparedness "Learn more about disaster preparedness from ScienceDirect's AI-generated Topic Pages") and response. The purpose of this study was to explore the facilitators of and barriers to such collaboration through a case study of a [multidisciplinary research](https://www-sciencedirect-com.proxy.library.upenn.edu/topics/earth-and-planetary-sciences/multidisciplinary-research "Learn more about multidisciplinary research from ScienceDirect's AI-generated Topic Pages") initiative at an urban East Coast university in the United States. Using an applied qualitative approach, we conducted individual semi-structured interviews with initiative members to explore facilitators and barriers to natural disaster preparedness and response, and initiative members' attitudes, perceptions, and expectations regarding multidisciplinary collaboration. We identified several common themes across natural disaster preparedness and response efforts and multidisciplinary research collaborations, such as greater human and financial resources. Additionally, we identified several themes unique to perceptions of multidisciplinary research collaboration, such as the importance of clearly defined structures, and the needs of all parties being met. Findings may serve as a framework for multidisciplinary academic collaborations preparing for and responding to natural disasters, as well as multidisciplinary collaboration in general.
