---
title: "Improved Relationship Quality, Equitable Gender Attitudes, and Reduced Alcohol Abuse as Key Mechanisms to Reduce Intimate Partner Violence in the Bandebereho Couples’ Randomized Trial in Rwanda"
type: "article"
author: "Ruti G. Levtov, Kate Doyle, Jeffrey B. Bingenheimer, <strong>Shaon Lahiri</strong>, Shamsi Kazimbaya, Emmanuel Karamage, Felix Sayinzoga, Merab Mutoni, Claude H. Rubayita, Gary Barker"
year: "2022"
publication: "Prevention Science"
doi: "https://doi.org/10.1007/s11121-022-01445-6"
toc: false
categories:
  - behavior change
  - gender norms
  - intimate partner violence
  - Rwanda
  - structural equation modeling
---

## Citation (APA 7)

> Levtov, R. G., Doyle, K., Bingenheimer, J. B., Lahiri, S., Kazimbaya, S., Karamage, E., \... & Barker, G. (2022). Improved Relationship Quality, Equitable Gender Attitudes, and Reduced Alcohol Abuse as Key Mechanisms to Reduce Intimate Partner Violence in the Bandebereho Couples' Randomized Trial in Rwanda. *Prevention science*, *23*(8), 1495-1506.

## Abstract

Over the past decade, there has been rapid growth in the evidence for programs to prevent or reduce intimate partner violence (IPV)--the most common form of men's violence against women. IPV interventions targeting heterosexual couples have shown significant impact. However, our understanding of how these interventions achieve their impacts on violence--the mechanisms through which change occurs--remains limited. Using data from two follow-up rounds of a randomized controlled trial of the Bandebereho intervention in Rwanda, we constructed conceptually driven structural equation models to represent the processes by which hypothesized mediating variables linked treatment assignment to IPV. We found significant differences in the expected direction between the intervention and control participants on all mediating variables, including men's alcohol use, communication frequency, emotional closeness, frequency of quarreling, and men's attitudes related to gender and violence. Several mechanisms--more positive couple dynamics including emotional closeness and communication frequency; men's gender-equitable attitudes; men's alcohol use--accounted for the largest proportions of the effect of assignment to the Bandebereho intervention on IPV. Overall, our findings highlight that no one particular component is driving the reductions in violence; instead, the multiple components and pathways account for the intervention's effects, suggesting that the holistic nature of the intervention may be integral to its positive impact. The Bandebereho trial from which data was used in this analysis was registered on [ClinicalTrials.gov](https://clinicaltrials.gov/) prior to completion ([NCT02694627](https://clinicaltrials.gov/ct2/show/NCT02694627)).
