---
title: "Does the Belief That Contraceptive Use Causes Infertility Actually Affect Use? Findings from a Social Network Study in Kenya"
type: "article"
author: "Erica Sedlander, Jeffrey B. Bingenheimer, <strong>Shaon Lahiri</strong>, Mary Thiongo, Peter Gichangi, Wolfgang Munar, Rajiv Rimal"
year: "2021"
publication: "Studies in Family Planning"
doi: "https://doi.org/10.1111/sifp.12157"
toc: false
categories:
  - social norms 
  - kenya
  - modern contraception
  - fertility
  - social network
---

## Citation (APA 7)

> Sedlander, E., Bingenheimer, J. B., Lahiri, S., Thiongo, M., Gichangi, P., Munar, W., & Rimal, R. N. (2021). Does the belief that contraceptive use causes infertility actually affect use? Findings from a social network study in Kenya. *Studies in family planning*, *52*(3), 343-359.

## Abstract

The belief that contraceptive use causes infertility has been documented across sub-Saharan Africa, but its quantitative association with actual contraceptive use has not been examined. We collected and analyzed sociocentric network data covering 74 percent of the population in two villages in rural Kenya. We asked respondents to nominate people from their village (their network), and then we matched their network (alters) to the individual participant (ego) to understand how their beliefs and behaviors differ. We asked about contraceptive use and level of agreement with a statement about contraceptive use causing infertility. We calculated the average nominated network contraceptive use score and the average nominated network belief score. Holding the individual belief that contraceptive use causes infertility was associated with lower odds of using contraceptive (AOR = 0.82, *p* = \< 0.01); however, when one's own nominated network connections held this belief, the odds of using contraceptive were even lower (AOR = 0.75, *p* \<0.01). Our findings show that this belief is associated with lower odds of contraceptive use and highlights the role that other people in one's network play in reinforcing it. Sexual and reproductive health programs should address this misperception at the individual and social network level.
