---
title: "Achieving and Sustaining Change Through Capacity Building Train-the-Trainer Health Initiatives in Low- and Middle-Income Countries: A Systematic Review"
type: "article"
author: "Bobbi Snowden, <strong>Shaon Lahiri</strong>, Rebecca Dutton, Lindsay Morton"
year: "2022"
publication: "Journal of Continuing Education in the Health Professions"
doi: "https://doi.org/10.1097/CEH.0000000000000458"
toc: false
categories:
  - implementation science
  - train-the-trainer
  - developing countries
  - global health
  - sustainability
---

## Citation (APA 7)

> Snowden, B., Lahiri, S., Dutton, R., & Morton, L. (2022). Achieving and Sustaining Change Through Capacity Building Train-the-Trainer Health Initiatives in Low-and Middle-Income Countries: A Systematic Review. *Journal of Continuing Education in the Health Professions*, 10-1097.

## Abstract

### **Introduction**

Given the anticipated health challenges, forecasted deficiencies in the global health workforce, and steady demands to work through resource constraints, effective and efficient training approaches to build capacity are direly needed. Although train-the-trainer (T3) is not a new approach, there has been considerable interest in using it to develop and sustain capacity, particularly in low- and middle-income countries. This systematic review aimed to better understand the factors to achieve and sustain change across multiple countries and levels through T3 approaches.

### **Methods**

A literature search was conducted of six scholarly, peer-reviewed, and gray literature databases. Data were extracted for the study method, design, characteristics, and implicit or explicit factors related to maximizing the likelihood of achieving and sustaining change. An existing conceptual framework for T3 interventions in global health guided the thematic analysis. The framework consisted of five factors pertinent to capacity building T3 initiatives: Talent, Resources, Alignment, Implementation, and Nurture and Development.

### **Results**

Twenty-two studies met the inclusion criteria. The T3 training spanned all geographical regions, but interventions were most prevalent in sub-Saharan Africa (46%). Nearly all studies (68%) quantitatively examined change at the individual level (95%), but some studies also explored change at the organizational (77%) and institutional (23%) levels. *Implementation* and *Nurture/Development* were the two most salient factors in achieving and sustaining change. The greatest hindrances involved *Resources* and *Context*, an additional theme that the data identified.

### **Discussion**

The findings and recommendations from this first systematic review exploring antecedents influencing change through health-related T3 interventions can inform training and capacity-building investments, improve existing T3 initiatives, and steer planning for future approaches.
